### ISSUE TITLE
Issue with Dice selecting

### ISSUE THREAD

**Issue by cmolleur** [cmolleur/yahtzee#1]
Right now, when I select certain dice, those dice do not reshuffle, which is exactly what I want. The problem is, those dice that are NOT selected, do shuffle, but they all shuffle to the same dice.

I'm also trying to write a rule function at the top to say that if the data of that dice image is equal to a specific number, I'm eventually going to add those up.

**Comment by rapala61** [comment]
Ill help you after the outcomes metting

**Comment by rapala61** [comment]
in person
