### ISSUE TITLE
Find values

### ISSUE THREAD

**Issue by cmolleur** [cmolleur/yahtzee#2]
I'm trying to get a checker working that will say if the selected elements have a matching value or the same number, adds those up. The issue is, i can find out how many dice are selected with that number on the first roll, but rolls 2 and 3 are creating a bug somewhere.

**Comment by rapala61** [comment]
Try creating a checker function that will loop through all selected dice, then grab their value and add it in every iteration. example:

```
function fun() {
    var selected = $('.selected');
    var total = 0;
    for(var i=0; i<selected.length; i++){
        var diceValue = $(selected[i]).attr('data-value');
        total += parseInt(diceValue);
    }
    return total;
}
```

**Comment by cmolleur** [comment]
I actually played with this some more and found that the issue isn't about the 2nd or 3rd roll,  is more about changing your dice half-way through. If you want to select the 1s, you need to do that from the beginning. Otherwise it'll return false.
